name: rohit.io
port: 4000
highlighter: rouge
lsi: false
#DEFAULT permalink: /:year/:month/:day/:title.html
permalink: /blog/:title.html
# Pagination configuration
paginate: 15
paginate_path: "page/:num"

markdown: rdiscount
# enables SmartyPants (nice curly quotation marks, em/en dashes, elipses, etc):
rdiscount:
  extensions: [smart]
# Since GH pages override this to "true", we test this value to see if we are running locally
safe: false
gems: 
  - 'jekyll-redirect-from'
  - 'jemoji'
  - 'jekyll-lunr-js-search'
# jekyll-lunr-js-search --> full-text search using JavaScript
lunr_search:
  excludes:
    - index.html
    - rss.xml
    - atom.xml
    - about/*
    - archive/*
    - res/*

website: 'www.rohit.io'
publisher: 'https://www.facebook.com/rohit01io'
default_home_thumbnails:
  - 'vivekananda.png'
  - 'best_version.png'
  - 'crazy_ones.png'
  - 'be_the_change.png'
